name: user_auth
description: Handy flutter plugin that help with user-backend-auth, written in pure dart code.
version: 1.1.1+4
homepage: https://github.com/MohamedSayed95/user_auth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2

flutter:
  plugin:
    platforms:
      android:
        package: net.msayed.user_auth
        pluginClass: UserAuthPlugin
      ios:
        pluginClass: UserAuthPlugin
