name: user_auth
description: Flutter user authentication with back-end handler.
version: 0.0.3
authors: 
- Creator <creative.mohamed.sayed@gmail.com>
homepage: https://github.com/MohamedSayed95/user_auth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # shared_preferences: 0.5.4+6
  dio: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: net.msayed.user_auth
    pluginClass: UserAuthPlugin
    platforms:
      android:
        package: net.msayed.user_auth
        pluginClass: UserAuthPlugin
      ios:
        pluginClass: UserAuthPlugin