name: user_auth
description: Dart - Backend user auth helpe, with common methods
version: 1.2.0
homepage: https://github.com/MohamedSayed95/user_auth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
